<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<title>{Title}{block:PostSummary} | {PostSummary}{/block:PostSummary}{block:SearchPage} | {lang:Search results for SearchQuery}{/block:SearchPage}</title>	
	<meta name="description" content="{MetaDescription}" />
	<meta name="text:DisqusId" content="" />
	<meta name="text:TwitterId" content="" />
    
	<link rel="shortcut icon" href="{Favicon}" />
	<link rel="alternate" type="application/rss+xml" title="{Title}" href="{RSS}" />
	<link rel="stylesheet" type="text/css" media="all" href="http://joostory-theme.googlecode.com/git/css/joostory.css">
	<link rel="stylesheet" type="text/css" media="all" href="http://joostory-theme.googlecode.com/git/lib/prettify/prettify.css">
	<link rel="stylesheet" type="text/css" media="all" href="http://joostory-theme.googlecode.com/git/lib/prettify/sunburst.css">
	
	<!-- Styles -->
	<style type="text/css">
	  {CustomCSS}
	</style>

<!--[if IE]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script src="http://joostory-theme.googlecode.com/git/lib/prettify/prettify.js"></script>
	<script>
		$(document).ready(function() {
			prettyPrint();
		});
	</script>
</head>
<body>

<div class="header">
    <h1 class="title"><a href="/" title="{Title}">{Title}</a></h1>
	<div class="sites" class="navigation">
		<ul>
		</ul>
	</div>
</div>
<div class="body">

    <div class="sidebar">
        <div class="sidebox" style="text-align:center;">
		  <div style="padding:10px 0;">
			<img src="{PortraitURL-128}">
		  </div>
		  {block:IfTwitterId}
            <a href="https://twitter.com/{text:TwitterId}" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @{text:TwitterId}</a>
		  {/block:IfTwitterId}
        </div>

        <div class="sub navigation">
            <ul class="sidebox">
        		<li><a href="http://www.google.com/reader/" title="Go to RSS Reader" target="_blank">RSS Reader</a></li>
        		<li><a href="http://www.google.com/analytics" title="Go to Analytics" target="_blank">Analytics</a></li>
        		<li><a href="http://www.google.com/adsense/" title="Go to Adsense" target="_blank">Adsense</a></li>
        		<li><a href="http://appengine.google.com/" title="Go to Google App Engine" target="_blank">App Engine</a></li>
        	</ul>
            
        	<a style="width:174px;height:31px;margin:0 auto;" href="http://mypeople.daum.net/" target="_blank" onclick="window.open(this.href, '', 'width=700px,height=510px');return false;"><img src="http://mimg.daum-img.net/10mail/b_mypeople.gif" /></a>
        </div>
    </div>
     
    <div class="contents">
        
    {block:Posts}
        <div class="content posts">

            <div class="post_date"><abbr>{block:Date}<a href="{Permalink}">{DayOfMOnth}{DayOfMonthSuffix} {ShortMonth} {Year}</a>{/block:Date}</abbr></div>
        
            {block:Text}
            {block:Title}<h2><a href="{Permalink}">{Title}</a></h2>{/block:Title}
            {Body}
            {/block:Text}
          
           {block:Photo}
              <div class="media">{LinkOpenTag}<img src="{PhotoURL-500}" alt="{PhotoAlt}" />{LinkCloseTag}</div>
              {block:Caption}<div class="photoCaption">{Caption}</div>{/block:Caption}
           {/block:Photo}
          
           {block:Photoset}
              <div class="media">{Photoset-500}</div>
              {block:Caption}<div class="caption">{Caption}</div>{/block:Caption}
           {/block:Photoset}
          
           {block:Quote}
              <div id="quoteText"><h2>{Quote}</h2></div>
              {block:Source}<div id="quoteSource"><p>&mdash;{Source}</p></div>{/block:Source}
           {/block:Quote}
    
           {block:Link}
              <h2><a href="{URL}" {Target}>{Name}</a></h2>
              {block:Description}
              <div>{Description}</div>
              {/block:Description}
           {/block:Link}       
          
          {block:Chat}
             {block:Title}<h2>{Title}</h2>{/block:Title}
             <ul class="chat">
                {block:Lines}
                <li>{block:Label}<strong>{Label}</strong>{/block:Label} {Line}</li>
                {/block:Lines}
             </ul>
          {/block:Chat}
    
          {block:Audio}
             <div class="audioleft">
                <div class="audioc">
                <div class="audio">{AudioPlayerBlack}</div>
                </div>
             </div>
             <div class="audioright"> 
                <div class="audioCaption">{block:Artist}<b>{Artist}</b>{/block:Artist}
    <p>&mdash;{block:TrackName}{TrackName}{/block:TrackName}</p>
                </div>
             </div>
             <div class="audioClear"></div>
             <div class="audioContainer">
                {block:Caption}{Caption}{/block:Caption}
             </div>
          {/block:Audio}
         
          {block:Video}
             <div class="media">{Video-500}</div>
             {block:Caption}<div>{Caption}</div>{/block:Caption} 
          {/block:Video}
          
          {block:Answer}
             <h3>{Asker} asked: {Question}</h3>
             {Answer}
          {/block:Answer}
          
            {block:HasTags}
            <div class="post_meta">
                <div class="tags">
                    <div class="tags_title">Tags : </div>
                    <ul>
                    {block:Tags}
                        <li><a href="{TagURL}">{Tag}</a></li>
                    {/block:Tags}
                    </ul>
                </div>
            </div>
            {/block:HasTags}
            
            
            {block:PermalinkPage} 
            <div id="disqus_thread"></div>
            {/block:PermalinkPage}
        </div>
    {/block:Posts}

        <div class="page">
        
        {block:Pagination}
            {block:PreviousPage}<a href="{PreviousPage}" class="prev_page">&#171; Previous</a>{/block:PreviousPage}
            {block:NextPage}<a href="{NextPage}" class="next_page">Next &#187;</a>{/block:NextPage}
        {/block:Pagination}



        {block:PermalinkPagination}
            {block:PreviousPost}<a href="{PreviousPost}" class="next_page">Next &#187;</a>{/block:PreviousPost}
            {block:NextPost}<a href="{NextPost}" class="prev_page">&#171; Previous</a>{/block:NextPost}
        {/block:PermalinkPagination}
        
        </div>

    </div>
     
</div>

<div class="footer">
    &copy; Joo
</div>


{block:PermalinkPage} 
<script type="text/javascript">
  var disqus_url = "{Permalink}";
  var disqus_title ="{block:PostTitle}{PostTitle}{/block:PostTitle}";
  /**
    * var disqus_identifier; [Optional but recommended: Define a unique identifier (e.g. post id or slug) for this thread] 
    */
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://${DisqusId}.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
{/block:PermalinkPage}

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

</body>
</html>
