<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<title>{Title}{block:SearchPage} ({lang:Search results for SearchQuery}){/block:SearchPage}{block:PermalinkPage}{block:PostSummary} — {PostSummary}{/block:PostSummary}{/block:PermalinkPage}</title>
	<meta name="description" content="{MetaDescription}" />

	{block:Hidden}
	<meta name="text:Disqus Shortname" content="">
	<meta name="text:Google Analytics ID" content="">
	<meta name="text:Google Adsense Publisher ID" content="">
	<meta name="text:Google Adsense Slot ID" content="">
	<meta name="if:Endless Scroll" content="1">
	{/block:Hidden}

	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<link rel="shortcut icon" href="{Favicon}" />
	<link rel="apple-touch-icon-precomposed" href="{PortraitURL-128}">
	<link rel="alternate" type="application/rss+xml" title="{Title}" href="{RSS}" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" media="all" href="http://static.tumblr.com/udrhgqb/PwWnqwu7i/joostory.css">

	<!-- Styles -->
	<style type="text/css">
		{block:PermalinkPage}
		.content h1 { font-size:28px; margin: 5px 0 25px; }
		{/block:PermalinkPage}
		{CustomCSS}
	</style>

	<!-- HTML5 Shiv -->
  <!--[if lt IE 9]>
      <script src="http://static.tumblr.com/hriofhd/Qj0m8pn7q/html5shiv.js"></script>
  <![endif]-->
	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-joostory navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/" title="{Title}">{Title}</a>
		</div>

		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<span class="hidden-xs glyphicon glyphicon-option-vertical" aria-hidden="true"></span>
						<span class="visible-xs-inline">더보기</span>
					</a>
          <ul class="dropdown-menu">
						<li><a href="/archive">Archive</a></li>
          </ul>
        </li>
			</ul>

			<form class="navbar-form navbar-right" role="search" method='get' action='/search'>
				<div class="form-group input-group">
					<input type="text" class="form-control" placeholder="Search" name="q" value="{SearchQuery}">
					<span class="input-group-btn">
						<button type="submit" class="btn btn-default">
							<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
							<span class="sr-only"></span>
						</button>
					</span>
				</div>
			</form>
		</div>
	</div>
</nav>

<div class="container">
  <div class="contents">
		{block:TagPage}
		<div class="page-header">
			<h3><span class="label label-tag-active"># {Tag}</span></h3>
		</div>
		{/block:TagPage}

		{block:SearchPage}
		<div class="page-header">
			<h3><span class="label label-default">{SearchQuery}</span> 으로 검색 ({SearchResultCount} 개)</h3>
		</div>
		{/block:SearchPage}

		{block:IfGoogleAdsensePublisherID}
			{block:IfGoogleAdsenseSlotID}
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<ins class="adsbygoogle"
				style="display:block;margin-bottom:20px"
				data-ad-client="{text:Google Adsense Publisher ID}"
				data-ad-slot="{text:Google Adsense Slot ID}"
				data-ad-format="auto"></ins>
			<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
			{/block:IfGoogleAdsenseSlotID}
		{/block:IfGoogleAdsensePublisherID}

		{block:NoSearchResults}
		<div class="content no-content">
			검색 결과가 없습니다.
		</div>
		{/block:NoSearchResults}

    {block:Posts}
      <div class="content post">

        <div class="post_date"><abbr>{block:Date}<a href="{Permalink}">{DayOfMOnth}{DayOfMonthSuffix} {ShortMonth} {Year}</a>{/block:Date}</abbr></div>

        {block:Text}
          {block:Title}<h1><a href="{Permalink}">{Title}</a></h1>{/block:Title}
          {Body}
        {/block:Text}

        {block:Photo}
          <div class="media">{LinkOpenTag}<img src="{PhotoURL-500}" alt="{PhotoAlt}" />{LinkCloseTag}</div>
          {block:Caption}<div class="photoCaption">{Caption}</div>{/block:Caption}
        {/block:Photo}

        {block:Photoset}
          <div class="media">{Photoset}</div>
          {block:Caption}<div class="caption">{Caption}</div>{/block:Caption}
        {/block:Photoset}

        {block:Quote}
          <div id="quoteText"><h1>{Quote}</h1></div>
          {block:Source}<div id="quoteSource"><p>&mdash;{Source}</p></div>{/block:Source}
        {/block:Quote}

        {block:Link}
          <div class="link">
            <h1><a href="{URL}" {Target}>{Name}</a></h1>
          </div>
          {block:Description}
          <div>{Description}</div>
          {/block:Description}
        {/block:Link}

        {block:Chat}
          {block:Title}<h1>{Title}</h1>{/block:Title}
          <ul class="chat">
            {block:Lines}
            <li>{block:Label}<strong>{Label}</strong>{/block:Label} {Line}</li>
            {/block:Lines}
          </ul>
        {/block:Chat}

        {block:Audio}
          <div class="audioleft">
            <div class="audioc">
            <div class="audio">{AudioPlayerBlack}</div>
            </div>
          </div>
          <div class="audioright">
            <div class="audioCaption">{block:Artist}<b>{Artist}</b>{/block:Artist}
          <p>&mdash;{block:TrackName}{TrackName}{/block:TrackName}</p>
            </div>
          </div>
          <div class="audioClear"></div>
          <div class="audioContainer">
            {block:Caption}{Caption}{/block:Caption}
          </div>
        {/block:Audio}

        {block:Video}
          <div class="media">{Video-500}</div>
          {block:Caption}<div>{Caption}</div>{/block:Caption}
        {/block:Video}

        {block:Answer}
          <h3>{Asker} asked: {Question}</h3>
          {Answer}
        {/block:Answer}

        {block:HasTags}
        <div class="post_meta">
					<span class="glyphicon glyphicon-tags tags_title" aria-hidden="true"><span class="sr-only">Tags</span></span>
	        {block:Tags}
	        <a href="{TagURL}"><span class="label label-tag">{Tag}</span></a>
	        {/block:Tags}
        </div>
        {/block:HasTags}

        {block:PermalinkPage}
					{block:IfDisqusShortname}
						<div id="disqus_thread"></div>
					{/block:IfDisqusShortname}
        {/block:PermalinkPage}
      </div>
    {/block:Posts}

  </div>

	{block:Pagination}
	<nav>
		<ul class="pager">
			{block:PreviousPage}
			<li class="previous">
				<a href="{PreviousPage}"><span aria-hidden="true">&larr;</span> Previous</a>
			</li>
			{/block:PreviousPage}
			{block:NextPage}
			<li class="next"><a href="{NextPage}">Next <span aria-hidden="true">&rarr;</span></a></li>
			{/block:NextPage}
		</ul>
	</nav>
	{/block:Pagination}

	{block:PermalinkPagination}
	<nav>
		<ul class="pager">
			{block:NextPost}
			<li class="previous"><a href="{NextPost}"><span aria-hidden="true">&larr;</span> Previous</a></li>
			{/block:NextPost}

			{block:PreviousPost}
			<li class="next"><a href="{PreviousPost}">Next <span aria-hidden="true">&rarr;</span></a></li>
			{/block:PreviousPost}
		</ul>
	</nav>
    {/block:PermalinkPagination}

</div>

<footer class="footer text-center">
	&copy; Joo
</footer>

{block:IndexPage}
	{block:IfEndlessScroll}
	<script src="http://static.tumblr.com/udrhgqb/q1Inqwcm4/endless_scroll.js"></script>
	<script>
	$.tumblrEndlessScroll($(".contents"), $(".pager"), {CurrentPage});
	</script>
	{/block:IfEndlessScroll}
{/block:IndexPage}

{block:PermalinkPage}
	{block:IfDisqusShortname}
	  <script type="text/javascript">
	    (function() {
	     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
	     dsq.src = 'http://{text:Disqus Shortname}.disqus.com/embed.js';
	     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	    })();
	  </script>
	{/block:IfDisqusShortname}
{/block:PermalinkPage}

{block:IfGoogleAnalyticsID}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', '{text:Google Analytics ID}', 'auto');
  ga('send', 'pageview');
</script>
{/block:IfGoogleAnalyticsID}

</body>
</html>
